#!/bin/sh
nix-shell -p disko --run "disko --mode destroy,format,mount /nixos/nixos/disk-config.nix"
mkdir -p /mnt/etc/nixos
nixos-generate-config --root /mnt
cp /nixos/nixos/configuration.nix /mnt/etc/nixos/configuration.nix
nixos-install
