#!/bin/sh
nix --extra-experimental-features "nix-command flakes" run github:nix-community/disko -- --mode destroy,format,mount /home/nixos/nixos/disk-config.nix
mkdir -p /mnt/etc/nixos
nixos-generate-config --root /mnt
cp /nixos/nixos/configuration.nix /mnt/etc/nixos/configuration.nix
nixos-install
